name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          scale: [ 4 ]
    steps:
      - uses: actions/checkout@v2
      - name: Build and run containers
        run: docker-compose build; docker-compose up -d --scale php=${{ matrix.scale }}
      - name: Tests
        run: docker-compose exec -T php sh -lc "php /test/test.php ${{ matrix.scale }} 200"